version: '3'

services:
  backend:
    build: ./
    container_name: nestjs_api
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - nestjs_network

  db:
    image: postgres:14.8
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auto_report_pscd
    volumes:
      - postgres-backup:/var/lib/postgresql/data
    networks:
      - nestjs_network
    ports:
      - "5432:5432"

networks:
  nestjs_network:
    driver: bridge

volumes:
  postgres-backup: